### ISSUE TITLE
issue with evaluate

### ISSUE THREAD

**Issue by JieYuDai** [lochenchou/DORN_radar#7]
Why do you use dense depth as the standard when training, and sparse depth as the standard when evaluating？
What is the difference between the two

**Comment by JieYuDai** [comment]
How do you divide day, night and rain？

**Comment by lochenchou** [comment]
1. We suffer from the issue as descibed in "Radar-Camera Pixel Depth Association for Depth Completion" while using sparse depth for training, so the interpolated dense was used as the objective target when training. However, we show the evaluation result against sparse depths only is because sparse depth is the "real ground truth" while interpolated dense depth are augmented one. (The result would higher while evaluating with dense depth, you could try on your own.)

2. The day, night and rain scenes are divided by the description of each scene that could get from nuscenes api.
